dist: xenial
sudo: required

language: c++

compiler:
  - g++

#dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y automake sqlite3 build-essential autoconf libtool git libxml2 libxml2-dev sqlite libsqlite3-dev python-dev libbluetooth-dev libdbus-1-3 libdbus-1-dev libssl-dev
#  - sudo apt-get install gcc-4.9
#  - sudo apt-get install g++-4.9
#  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 49 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
#  - sudo update-alternatives --set gcc "/usr/bin/gcc-4.9"
  - export ENCODERS_HOME=`pwd`
  - export COVERALLS_REPO_TOKEN="qB3LrhoMhX0VajBpJ07kQ0ThWlSf1cWko"
  - export CXXFLAGS="${CXXFLAGS} -fprofile-arcs -ftest-coverage"
  - sudo pip install --user cpp-coveralls;
  - sudo pip install pyyaml;
  - export PATH=$PATH:${HOME}/.local/bin

script:
  - cd ${ENCODERS_HOME}/haggle 
  - ./autogen.sh
  - export CPPFLAGS="-DU_HAVE_STDINT_H=1 -DU_EXPORT= -DU_EXPORT2= -DU_IMPORT= -DU_CALLCONV="
  - ./configure --enable-gcov
  - make 
  - make test_thread 
  
after_script:
  - coveralls -r .. -b testsuite/test_thread -i haggle/src --verbose --gcov-options '\-lp';
